-- plugins configurations
require("plugins.colorscheme")
require("plugins.lualine")
require("plugins.treesitter")
require("plugins.cmp")
require("plugins.comment")
require("plugins.lsp")
require("plugins.telescope")
require("plugins.indentation")
require("plugins.git")
require("plugins.formatting")
require("plugins.harpoon")
