-- plugins configurations
require("plugins.colorscheme")
require("plugins.lualine")
require("plugins.treesitter")
require("plugins.completion")
require("plugins.comments")
require("plugins.lspconfig")
require("plugins.telescope")
require("plugins.indentation")
require("plugins.gitsigns")
require("plugins.formatting")
require("plugins.harpoon")
